Repository Project2048W25/Project2048-SOEN341_Project_W25, pull requests merged in 2025-03, with the labels that each got.

#74 11 task 2 fixed the DMs and added the css.
  chathaven/src/App.js
  chathaven/src/Pages/AdminView.jsx
  chathaven/src/Pages/MemberDM.jsx
  chathaven/src/Pages/MemberView.jsx
  chathaven/src/Pages/Sidebar.jsx
  chathaven/src/Pages/index.css
Labels: frontend

#91 Update Sprint2.md
  Sprint2/Sprint2.md
Labels: documentation

#111 added 15-task2-presence indicator feature
  chathaven/src/Pages/MemberDM.jsx
  chathaven/src/Pages/MembersList.jsx
  chathaven/src/Pages/Sidebar.jsx
  chathaven/src/Pages/index.css
Labels: sprint-3, backend, task

#120 Last Seen Indicator Shown When User is Offline
  chathaven/src/Pages/MemberDM.jsx
  chathaven/src/Pages/MembersList.jsx
  chathaven/src/Pages/Sidebar.jsx
  chathaven/src/services/authService.js
Labels: sprint-3, task
